<a href="https://colab.research.google.com/github/Mr-Katakitchen/ML-NTUA/blob/main/lab1/MM2024_25_Lab2_2_Crossvalidation_%CE%9CetricsForClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

⚠️
Επισημαίνεται ότι η σχεδίαση και το περιεχόμενο του notebook αποτελούν αντικείμενο πνευματικής ιδιοκτησίας.

# Τεχνικές διασταυρωμένης επικύρωσης

Οι τεχνικές διασταυρωμένης επικύρωσης (cross-validation techniques) χρησιμοποιούνται για την αξιολόγηση της απόδοσης των μοντέλων μηχανικής μάθησης, προσφέροντας **μια πιο αξιόπιστη και γενικευμένη εικόνα της απόδοσης τους σε άγνωστα δεδομένα**.

Αυτές οι τεχνικές βοηθούν *να αποφευχθεί η υπερπροσαρμογή (overfitting) ή η υποπροσαρμογή (underfitting)* και επιτρέπουν να *αξιολογήσουμε* την ικανότητα γενίκευσης του μοντέλου, δηλαδή το *πώς θα αποδώσει σε νέα, μη γνωστά δεδομένα*.

- Λόγοι Χρήσης των Τεχνικών Διασταυρωμένης Επικύρωσης:

  - Αξιολόγηση της Απόδοσης του Μοντέλου: Στην ανάπτυξη μοντέλων, είναι σημαντικό να αξιολογούμε πόσο καλά θα αποδίδει ένα μοντέλο σε νέα δεδομένα και όχι μόνο στα δεδομένα εκπαίδευσης. Η διασταυρωμένη επικύρωση προσφέρει μια πιο ρεαλιστική εκτίμηση του πραγματικού σφάλματος του μοντέλου.

  - Αντιμετώπιση της Μεροληψίας στην Εκπαίδευση και Δοκιμή: Αν χωρίσουμε τα δεδομένα μόνο μια φορά σε σύνολα εκπαίδευσης και δοκιμής, υπάρχει πιθανότητα τα δεδομένα αυτά να μην είναι αντιπροσωπευτικά ή να προκαλέσουν μεροληψία στην αξιολόγηση. Η διασταυρωμένη επικύρωση ελαχιστοποιεί αυτό το ρίσκο, κάνοντας πολλαπλές δοκιμές σε διαφορετικά υποσύνολα.
  - Αποφυγή Υπερπροσαρμογής (Overfitting): Η υπερπροσαρμογή συμβαίνει όταν το μοντέλο μαθαίνει υπερβολικά καλά τις λεπτομέρειες των δεδομένων εκπαίδευσης, αποδίδοντας άσχημα σε νέα δεδομένα. Η διασταυρωμένη επικύρωση βοηθά να εντοπιστεί αν το μοντέλο προσαρμόζεται υπερβολικά στα δεδομένα εκπαίδευσης και ελέγχει αν έχει την ίδια απόδοση σε διαφορετικά υποσύνολα των δεδομένων.

  - Χρήση Όλων των Δεδομένων για Εκπαίδευση και Δοκιμή: Σε σύνολα δεδομένων μικρού μεγέθους, η διασταυρωμένη επικύρωση επιτρέπει την καλύτερη αξιοποίηση των δεδομένων, διότι κάθε δείγμα μπορεί να χρησιμοποιηθεί τόσο για εκπαίδευση όσο και για δοκιμή σε διαφορετικά βήματα της διαδικασίας.

  - Βελτιστοποίηση Υπερπαραμέτρων: Κατά την επιλογή των βέλτιστων υπερπαραμέτρων ενός μοντέλου, η διασταυρωμένη επικύρωση χρησιμοποιείται για να συγκρίνουμε την απόδοση διαφορετικών συνδυασμών υπερπαραμέτρων και να επιλέξουμε τον καλύτερο.

Για τον πειραματισμό μας  θα χρησιμοποιήσουμε ως dataset το *Pima-Indians-diabetes*. Θα φορτώσουμε το dataset και θα το χωρίσουμε σε data και σε labels.

In [ ]:
from IPython.display import Image
from IPython.display import display

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# inline plotting instead of popping out
%matplotlib inline


# e.g., plot_decision_regions()
import os, sys
module_path = os.path.abspath(os.path.join('.'))
sys.path.append(module_path)


# Load CSV using Pandas from URL

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(url, names=names)
print(data.shape)

# separate array into input and output components
# X: Features Y: Labels

y = data['class']
X = data.drop('class', axis=1)

X.shape, y.shape

(768, 9)


((768, 8), (768,))

# Βασικές Τεχνικές Διασταυρωμένης Επικύρωσης

## Hold out cross validation

![alt text](https://www.kdnuggets.com/wp-content/uploads/dataiku-holdout-strategy.jpg)

Βήμα 1: Χωρίζουμε τα data kai ta labels σε training (70%) και σε testing set (30%)   
![](https://developers.google.com/static/machine-learning/crash-course/images/PartitionTwoSets.svg)

In [ ]:
from sklearn.model_selection import train_test_split
# hold out testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

X_train.shape, X_test.shape

((537, 8), (231, 8))

Βήμα 1: Έπειτα θα  χωρίζουμε το training set σε 70% και σε 30% όπου το 30% θα το χρησιμοποιήσουμε για validation  ![](https://developers.google.com/static/machine-learning/crash-course/images/PartitionThreeSets.svg)



In [ ]:
# hold out validation set
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=0)

X_train.shape, X_val.shape

((375, 8), (162, 8))

Χρησιμοποιoύμε το σύνολο επικύρωσης(validation set) για να αξιολογήσουμε τα αποτελέσματα από το σύνολο εκπαίδευσης. Στη συνέχεια, χρησιμοποιούμε το σύνολο δοκιμών για να ελέγξουμε ξανά την αξιολόγησή μας αφού το μοντέλο «περάσει» το σύνολο επικύρωσης.

Το παρακάτω σχήμα δείχνει αυτή τη νέα ροή εργασίας:

![](https://developers.google.com/static/machine-learning/crash-course/images/WorkflowWithValidationSet.svg)

Βήμα 2:  Για διαφορετικές υπερπαραμέτρους (n_neighbors = 1, 15, 50) θα εκπαιδεύσουμε έναν k-nearest neighbors classifier, χρησιμοποιώντας το training set με το validation set και θα τυπώσουμε τα αποτελέσματα

In [ ]:

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


best_k, best_score = -1, -1
clfs = {}

# hyperparameter tuning
for k in [1, 15, 51]:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_val)
    score = accuracy_score(y_val, y_pred)
    print('[{}-NN]\nValidation accuracy: {}'.format(k, score))
    if score > best_score:
        best_k, best_score = k, score
    clfs[k] = knn

[1-NN]
Validation accuracy: 0.7098765432098766
[15-NN]
Validation accuracy: 0.7901234567901234
[51-NN]
Validation accuracy: 0.7345679012345679


Βήμα 3: Θα επιλέξουμε το καλύτερο αποτέλεσμα και θα το εφαρμόσουμε στα δεδομένα ελέγχου (test set)

In [ ]:
# performance reporting
y_pred= clfs[best_k].predict(X_test)

print('Test accuracy:', accuracy_score(y_test, y_pred), ', n_neighbors=',best_k)

Test accuracy: 0.7316017316017316 , n_neighbors= 15


Ένα σημαντικό μειονέκτημα της  holdout μεθόδου είναι ότι οι επιδόσεις της είναι ευαίσθητες στους τυχαίους διαχωρισμούς και σε μη βέλτιστες υπερπαραμέτρους. Αν θέσουμε n_neighbors = 15 χειροκίνητα τότε ίσως να παρατηρήσουμε ότι οδηγούμαστε σε καλύτερα αποτελέσματα.

In [ ]:
k=15
y_pred= clfs[k].predict(X_test)
print('Test accuracy: %.2f (n_neighbors=15 selected manually)' %
      (accuracy_score(y_test, y_pred)))

Test accuracy: 0.73 (n_neighbors=15 selected manually)


##K-fold Cross Validation

![alt text](https://www.kdnuggets.com/wp-content/uploads/dataiku-kfold-strategy.jpg)


Βήμα 1: Χωρίζουμε τα data kai ta labels σε training (70%) και σε testing set (30%)

In [ ]:
# hold out testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

X_train.shape, X_test.shape

((537, 8), (231, 8))

Για διαφορετικές υπερπαραμέτρους (n_neighbors = 1, 15, 50) θα εκπαιδεύσουμε έναν k-nearest neighbors classifier, χρησιμοποιώντας το training set μαζί με το k fold cross validation.

Βήμα 2:

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

best_k, best_score = -1, -1
clfs = {}

for k in [1, 15, 50]: # experiment different hyperparameter
    knn1 = KNeighborsClassifier(n_neighbors=k)
    knn1.fit(X_train, y_train)
    # K-Fold CV
    scores = cross_val_score(knn1, X_train, y_train, cv=10)
    print('[%d-NN]\nValidation accuracy: %.3f %s' % (k, scores.mean(), scores))
    if scores.mean() > best_score:
        best_k, best_score = k, scores.mean()
    clfs[k] = knn1

[1-NN]
Validation accuracy: 0.679 [0.68518519 0.68518519 0.72222222 0.7962963  0.64814815 0.64814815
 0.68518519 0.62264151 0.64150943 0.66037736]
[15-NN]
Validation accuracy: 0.741 [0.75925926 0.74074074 0.74074074 0.72222222 0.77777778 0.74074074
 0.68518519 0.71698113 0.77358491 0.75471698]
[50-NN]
Validation accuracy: 0.724 [0.7037037  0.74074074 0.74074074 0.68518519 0.7962963  0.75925926
 0.62962963 0.69811321 0.75471698 0.73584906]


Βήμα 3: To 10-fold Cross Validation  επίλεξε τον καλύτερο ταξινομητή (n_neighbors = 50 ), όπως αναμέναμε.
Μόλις επιλέξουμε τις σωστές τιμές υπερπαραμέτρων, επανεκπαιδεύουμε το μοντέλο στο πλήρες training set και λάβουμε μια τελική εκτίμηση απόδοσης για το test set.

In [ ]:
best_clf = clfs[best_k]
best_clf.fit(X_train, y_train)

# performance reporting
y_pred = best_clf.predict(X_test)
print('Test accuracy: %.2f (n_neighbors=%d selected by 10-fold CV)' %
      (accuracy_score(y_test, y_pred), best_k))

Test accuracy: 0.76 (n_neighbors=15 selected by 10-fold CV)


Συνήθως, ορίζουμε K = 10 στις περισσότερες εφαρμογές και  K = 5 για μεγαλύτερα σύνολα δεδομένων.  Όταν έχουμε πολύ μικρά σύνολα δεδομένων ορίσουμε  K = N, που αντιστοιχεί στο **leave-one-out cross validation**.

## Μετρικές για classification

### Ορθότητα
$\texttt{accuracy}(y, \hat{y}) = \frac{1}{n_\text{samples}} \sum_{i=0}^{n_\text{samples}-1} 1(\hat{y}_i = y_i)$


In [ ]:
from sklearn.metrics import accuracy_score
y_true = [0, 1, 0, 0, 1, 1]
y_pred = [0, 1, 1, 0, 0, 1]
accuracy_score(y_true, y_pred), accuracy_score(y_true, y_pred, normalize=False)

(0.6666666666666666, 4.0)

### Confusion Matrix

Ένας πίνακας σύγχυσης είναι ένας απλός τρόπος για να αξιολογήσoυμε οπτικά πόσο συχνά είναι σωστές οι προβλέψεις από έναν ταξινομητή.

Για δυαδικά προβλήματα, μπορούμε να τυπώσουμε  τα εξής: **true negatives, false positives, false negatives** και **true positives**.

In [ ]:
from sklearn.metrics import confusion_matrix
y_true = [0, 0, 0, 1, 1, 1, 1, 1]
y_pred = [0, 1, 0, 1, 0, 1, 0, 1]

tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
tn, fp, fn, tp

(2, 1, 2, 3)

In [ ]:
from sklearn.metrics import confusion_matrix
y_true = [0, 1, 0, 1, 2, 2, 0, 1, 0, 2]
y_pred = [0, 2, 1, 1, 1, 2 , 1, 0, 1, 2]

confusion_matrix(y_true, y_pred)

array([[1, 3, 0],
       [1, 1, 1],
       [0, 1, 2]])

###  Classification report

Απεικονίζει σε πίνακα το **precision**, το **recall** και το **f1-score** για κάθε κλάση του dataset.
Μπορούμε να δούμε και την κάθε μετρική χωριστά.

In [ ]:
from sklearn.metrics import classification_report
y_true = [0, 1, 2, 1, 1]
y_pred = [0, 0, 2, 1, 1]
target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(y_true, y_pred, target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.50      1.00      0.67         1
     class 1       1.00      0.67      0.80         3
     class 2       1.00      1.00      1.00         1

    accuracy                           0.80         5
   macro avg       0.83      0.89      0.82         5
weighted avg       0.90      0.80      0.81         5



## Μετρικές για Regression

$\text{MAE}(y, \hat{y}) = \frac{1}{n_{\text{samples}}} \sum_{i=0}^{n_{\text{samples}}-1} \left| y_i - \hat{y}_i \right|$

In [ ]:
# return loss : float or ndarray of floats => A non-negative floating point value (the best value is 0.0), or an array of floating point values, one for each individual target.


from sklearn.metrics import mean_absolute_error

y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]

mean_absolute_error(y_true, y_pred)



0.5

In [ ]:
y_true = [[0, 2], [-1, 1], [7, -6]]
y_pred = [[0, 1], [-1, 1], [8, -5]]


mean_absolute_error(y_true, y_pred)


# multioutputs: Defines aggregating of multiple output values. Array-like value defines weights used to average errors.

#‘raw_values’ :Returns a full set of errors in case of multioutput input.
# ‘uniform_average’ : Errors of all outputs are averaged with uniform weight.


mean_absolute_error(y_true, y_pred, multioutput='raw_values')

#mean_absolute_error(y_true, y_pred, multioutput=[0.3, 0.7])

array([0.33333333, 0.66666667])

$\text{MSE}(y, \hat{y}) = \frac{1}{n_\text{samples}} \sum_{i=0}^{n_\text{samples} - 1} (y_i - \hat{y}_i)^2$

In [ ]:
from sklearn.metrics import mean_squared_error
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
mean_squared_error(y_true, y_pred)



0.375

In [ ]:
y_true = [[0.5, 1],[-1, 1],[7, -6]]
y_pred = [[0, 2],[-1, 2],[8, -5]]
mean_squared_error(y_true, y_pred)

mean_squared_error(y_true, y_pred, multioutput='raw_values')


#mean_squared_error(y_true, y_pred, multioutput=[0.3, 0.7])

array([0.41666667, 1.        ])

$R^2(y, \hat{y}) = 1 - \frac{\sum_{i=0}^{n_{\text{samples}} - 1} (y_i - \hat{y}_i)^2}{\sum_{i=0}^{n_\text{samples} - 1} (y_i - \bar{y})^2}$

In [ ]:
from sklearn.metrics import r2_score
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
r2_score(y_true, y_pred)

y_true = [[0.5, 1], [-1, 1], [7, -6]]
y_pred = [[0, 2], [-1, 2], [8, -5]]
r2_score(y_true, y_pred, multioutput='variance_weighted')


y_true = [[0.5, 1], [-1, 1], [7, -6]]
y_pred = [[0, 2], [-1, 2], [8, -5]]
r2_score(y_true, y_pred, multioutput='uniform_average')


r2_score(y_true, y_pred, multioutput='raw_values')


r2_score(y_true, y_pred, multioutput=[0.3, 0.7])

0.9253456221198156